language: node_js
node_js: node
sudo: false

env:
  - MONGODB=3.2.13

services:
  - redis-server

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - npm install -g greenkeeper-lockfile@1

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - greenkeeper-lockfile-update
  - npm prune

script:
  - npm run cover-memory
  - npm run cover-mongo
  - npm run build
  - ./node_modules/tslint/bin/tslint --project ./tsconfig.json -c ./tslint.travis.json
  - npm run duplication -- --limit=0.01

after_script:
  - pkill mongod

after_success:
  - npm prune --production
  - npm run semantic-release
  - greenkeeper-lockfile-upload
